language: node_js
node_js:
  - '8.5.0'
  - '6.11.2'
  - '5.11'
  - '4.4'
  - '4.2'
branches:
  only:
  - master
  - /^v[0-9](\.[0-9]+)(\.[0-9]+)?$/
script: npm run check
before_deploy: npm run build
deploy:
  provider: npm
  email: daniel.pazsoldan@gmail.com
  skip_cleanup: true
  api_key:
    secure: lM1Xaq8a+kvLRQP1Hd4NzWa7f7Cf7Nv5RrtbcUMaobGA1ajkfKxJJ21gaLjAmjSQEY+ZsSsXVktQ4QJ9dtWGUKIfklGRvDCfWdfK3NA4cHEFgK+tTT/689vIrFY27Q1ZJ6YJZDVYDmrX7WJoBeg1lSuTseSgWJ8XOl5d7ctLhIjt9Py6Sy+Zh4yMsTm4H4kWs9cqmqoWIw21Tf+z+wiRSR0ipMoMkavAShj5bQTvuXU3/z1V//N7UTUrB34wK2kqcOu2qdL70o05aYClYfo+B2aFvp0ZVYgamh/tbjR9gQqGDfoAvJy+FvSGjTB+ZP8x0ZjTeCDnKFVHEE3dqvzZYb9FKA2ZTVXT5ZG9XdJ49Qpocpkz8JSpxJ6yKMbcynzsJJ8CEEJatY9yBqH5BFX+2kjlokwxJ9Dz6/TVwiSfleIxTy20x7DWXWwBWu5wvsLedIrkgP3anK6jN+rBiRRC8+bq3XDZDt3AglIdSIkctiXUxIXa74I0oMgjQSBUS6+OuXpXc2yHWwb6+z8TFG/KpOJethAgfKyW/esLAZAPqoyvR2eT/J6kDWVGwr3Wy8JKZuHHGAfRREdqwhe1zCOxbdpvKewbpwGWbA0/aO9rjzCaXRmdXVTIucOJC9Nt4pBHF+y888vu1m7eTf1tBotmKt/hwJK5SakTjWn6N9bBlxo=
  on:
    tags: true
    repo: danpaz/bodybuilder
    branch: master
    node: '6.11.2'
